\src\main\java\com\mg\gra\GraApplication.java
\src\main\java\com\mg\gra\adapters\controllers\ProducerController.java
\src\main\java\com\mg\gra\application\MovieDataParser.java
\src\main\java\com\mg\gra\application\dto\MovieData.java
\src\main\java\com\mg\gra\application\service\MovieImportService.java
\src\main\java\com\mg\gra\application\service\ProducerService.java
\src\main\java\com\mg\gra\application\useCase\FindProducerWithAwardIntervalsUseCase.java
\src\main\java\com\mg\gra\application\useCase\ImportMoviesFromCSVUseCase.java
\src\main\java\com\mg\gra\domain\gateways\MovieGateway.java
\src\main\java\com\mg\gra\domain\gateways\ProducerGateway.java
\src\main\java\com\mg\gra\domain\models\Movie.java
\src\main\java\com\mg\gra\domain\models\Producer.java
\src\main\java\com\mg\gra\infrastructure\configs\MovieConfig.java
\src\main\java\com\mg\gra\infrastructure\configs\ProducerConfig.java
\src\main\java\com\mg\gra\infrastructure\gateways\MovieGatewayImpl.java
\src\main\java\com\mg\gra\infrastructure\gateways\ProducerGatewayImpl.java
\src\main\java\com\mg\gra\infrastructure\mapper\MovieMapper.java
\src\main\java\com\mg\gra\infrastructure\mapper\ProducerMapper.java
\src\main\java\com\mg\gra\infrastructure\model\MovieEntity.java
\src\main\java\com\mg\gra\infrastructure\model\ProducerEntity.java
\src\main\java\com\mg\gra\infrastructure\repository\MovieJpaRepository.java
\src\main\java\com\mg\gra\infrastructure\repository\ProducerJpaRepository.java
\src\main\java\com\mg\gra\infrastructure\runner\MovieImportStartupRunner.java
\src\main\resources\application.yml
\src\main\resources\data\movielist.csv
\src\main\resources\db\migration\V1__create_producer_table.sql
\src\main\resources\db\migration\V2__create_movie_table.sql
\src\main\resources\META-INF\additional-spring-configuration-metadata.json
\src\test\java\com\mg\gra\GraApplicationTest.java
\src\test\java\com\mg\gra\integration\ImportMoviesFromCsvIntegrationTest.java
\src\test\java\com\mg\gra\unit\ImportMoviesFromCsvUseCaseUnitTest.java
\src\test\resources\application-test.yml
