movies.csv.path: src/main/resources/data/movielist.csv

spring:
    application:
        name: golden_raspberry_awards

    datasource:
        url: jdbc:h2:mem:golden_raspberry_awards
        driverClassName: org.h2.Driver

    h2:
        console:
            enabled: true
            path: /h2-console

    jpa:
        hibernate: 
            ddl-auto: none
            show-sql: true
            format_sql: true

    flyway:
        cleanDisabled: false
        enabled: true
        locations: classpath:db/migration
        
logging:
    level:
        com.mg.gra: DEBUG
    file:
        encoding: UTF-8
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
