movies.csv.path: src/main/resources/data/movielist.csv

spring:
    application:
        name: golden_raspberry_awards

    datasource:
        url: jdbc:h2:mem:golden_raspberry_awards
        username: sa
        password: password
        driverClassName: org.h2.Driver
    
    h2:
        console.enabled: true

    jpa:
        hibernate: 
            ddl-auto: none
            show-sql: true
            format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

    flyway:
        enabled: true
        locations: classpath:db/migration
        
logging:
    level:
        root: INFO